apiVersion: batch/v1
kind: Job
metadata:
  name: pvc-data-migrator
  namespace: scrapyd
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrator
          image: busybox:latest
          command: ["cp", "-av", "/source/.", "/destination/."]
          volumeMounts:
            - mountPath: /source
              name: source-volume
            - mountPath: /destination
              name: destination-volume
      volumes:
        - name: source-volume
          persistentVolumeClaim:
            claimName: scrapyd-pvc
        - name: destination-volume
          persistentVolumeClaim:
            claimName: scrapyd-data
