apiVersion: v1
kind: Pod
metadata:
  name: pvc-data-migrator
  namespace: pihole
spec:
  containers:
    - name: migrator
      image: busybox:latest
      command: ["cp", "-av", "/source/.", "/destination/."]
      volumeMounts:
        - mountPath: /source
          name: source-volume
        - mountPath: /destination
          name: destination-volume
  volumes:
    - name: source-volume
      persistentVolumeClaim:
        claimName: pvc
    - name: destination-volume
      persistentVolumeClaim:
        claimName: pihole-data
