apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: cilium
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
      valuesKey: values.yaml
