apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml
    options:
      namespace: kube-system
resources:
  - helmrepo.yaml
  - helmrelease.yaml
