apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml
resources:
  - helmrepo.yaml
  - helmrelease.yaml
