apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: ghcr.io/wavefrontset/scrapyd:1.6.0-py3.13
          args: ["-l", "-"]
          ports:
            - containerPort: 6800
          resources: {}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_DRIVERNAME
              value: postgresql+psycopg2
            - name: DB_HOST
              value: cnpg-cluster-rw.cnpg-cluster.svc
            - name: DB_PORT
              value: '5432'
            - name: DB_DATABASE
              value: scrapydb
          volumeMounts:
            - name: scrapyd-conf
              mountPath: /etc/scrapyd/scrapyd.conf
              subPath: scrapyd.conf
            - name: scrapyd
              mountPath: /src/eggs
              subPath: eggs
            - name: scrapyd
              mountPath: /var/lib/scrapyd/logs
              subPath: logs
            - name: scrapyd
              mountPath: /var/lib/scrapyd/items
              subPath: items
            - name: scrapyd
              mountPath: /var/lib/scrapyd/db
              subPath: db
      restartPolicy: Always
      volumes:
        - name: scrapyd-conf
          configMap:
            name: scrapyd-conf
        - name: scrapyd
          persistentVolumeClaim:
            claimName: scrapyd-data
