apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scrapyd
configMapGenerator:
  - name: scrapyd-conf
    files:
      - scrapyd.conf
resources:
  - namespace.yaml
  - scrapyd-pvc.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ingress.yaml
