apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cluster-role.yaml
  - config-map.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: homepage-values
    namespace: flux-system
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
