---
machine:
  network:
    nameservers:
      - 192.168.2.1
      - 8.8.8.8
      - 1.1.1.1
    interfaces:
      - interface: enp1s0
        # - interface: enp0s31f6 # For dells
        dhcp: true
        vip:
          ip: 192.168.2.19
