apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-snapshots
spec:
  cron: "4 2 * * *"  # daily at 02:04
  task: "snapshot"
  groups:
    - default
  retain: 7
  concurrency: 2
  labels:
    kind: daily
