apiVersion: v1
data:
    QUERY_LOG_TARGET: ENC[AES256_GCM,data:9tHjDv+sLFH0ABrR31O7PYJSGUfDdWGsozXlXO7IG7rF9UFShx+/7QM2lKmabvbCYg97L4sfNw+CpbV6rRbZNeUIQPs7q8MpL5DV4IsUXhT5DD5M/m2KcK+lf0IcYdO7LI7W8zyPY+ouNuw02QqCRZbDYcWavfvF3VLc95Kyido=,iv:avlz1bcL0hturKDUyQjB02OQI2zHXI32+vXW8vfOmBw=,tag:85w8MQnb+8FtR7KcVtGJrg==,type:str]
kind: Secret
metadata:
    name: blocky-ui-secret
    namespace: blocky
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q1JiZHd2eEMzdzVLQzVN
            VGhla0FoZlh4aklzZTg4TWEwQUhXRk1vSWljCkZoTWx6ZzgwQlVHYWUvR1lLWmpu
            cTMzUWU4T1RCZXpGYTlZTzlWUWNnaE0KLS0tIGQvL1dJdEZsWkpMckpVZHRCK1VY
            anc5OXZxU2RYckZJTG5qTVVUakhtUTgKIQvKBPwZ8VvNRk294OugdxbI7pJXv54E
            sclIQ7pMsQo2Z/zBiNRxZcYIbGXJuNYYwGu+VXZQmJDHRe6rx20yEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T22:58:51Z"
    mac: ENC[AES256_GCM,data:uNBwgmNaXtyNBrJNR0RvuGgB48auMnTBbK1Mz5nvM7F9R1HDr6ucsyIA9fAEsSVCdWqfRS6gbXI+G6eBwL9Ri4RD51YZvxRJPk+4v9zCujRWNlnBJK1//6JTdxkd+ZU2AFovGamEIe2V4TwZathgfqdwUkYoKqPz7wGi5P6SYDc=,iv:7uyDAnXy20zDYjlK84YmQ30om9MwCv3wXtVUiisOH9Y=,tag:zSQ9+YEL+3c1r0Ep6yxqSA==,type:str]
    version: 3.13.0
