apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
data:
  config.yml: |
    upstreams:
      groups:
        default:
          - 192.168.2.1
          - 1.1.1.1
          - 8.8.8.8

    blocking:
      blockType: nxDomain
      denylists:
        ads:
          - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Win10Telemetry
          - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
          - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
          - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist
          - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/MS-Office-Telemetry
      allowlists:
        ads:
          - https://raw.githubusercontent.com/m0zgen/dns-hole/master/whitelist.txt
          - https://raw.githubusercontent.com/m0zgen/dns-hole/master/vendors-wl/microsoft.txt
          - https://raw.githubusercontent.com/m0zgen/dns-hole/master/vendors-wl/google.txt
          - https://raw.githubusercontent.com/m0zgen/dns-hole/master/regex/common-wl.txt
      clientGroupsBlock:
        default:
          - ads

    caching:
      cacheTimeNegative: 1m

    filtering:
      queryTypes:
        - AAAA


    customDNS:
      customTTL: 1h
      mapping:
        blocky.homelab: 192.168.1.16
        pihole.homelab: 192.168.1.17
        homelab: 192.168.1.18

    ports:
      dns: 53
      http: 4000

    bootstrapDns: 1.1.1.1

    prometheus:
      enable: true
      path: /metrics

    queryLog:
      type: postgresql
      logRetentionDays: 30
      target: postgres://cnpg-pooler-rw.cnpg-cluster.svc:5432/blockydb
