apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blocky
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - db-secret.sops.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - redis-deployment.yaml
  - redis-service.yaml
