controllers:
  blocky:
    type: deployment
    replicas: 3
    containers:
      app:
        image:
          repository: spx01/blocky
          tag: v0.31.0
        resources:
          requests:
            cpu: 20m
            memory: 75Mi
          limits:
            memory: 128Mi
        envFrom:
          - secretRef:
              name: db-secret
        env:
          TZ: Europe/Berlin
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/blocking/status
                port: 4000
              failureThreshold: 3
              periodSeconds: 30
              timeoutSeconds: 10
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/blocking/status
                port: 4000
              failureThreshold: 3
              periodSeconds: 10
              timeoutSeconds: 1
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/blocking/status
                port: 4000
              failureThreshold: 30
              periodSeconds: 5
              timeoutSeconds: 1
  ui:
    type: deployment
    containers:
      app:
        image:
          repository: gabrielduartem/blocky-ui
          tag: "1.8.1"
        resources:
          requests:
            cpu: 1m
            memory: 100Mi
          limits:
            memory: 128Mi
        env:
          BLOCKY_API_URL: http://blocky-svc:4000
          QUERY_LOG_TYPE: postgresql
        envFrom:
          - secretRef:
              name: blocky-ui-secret
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 3000
              failureThreshold: 3
              periodSeconds: 30
              timeoutSeconds: 10
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 3000
              failureThreshold: 3
              periodSeconds: 10
              timeoutSeconds: 1
  redis:
    type: deployment
    containers:
      app:
        image:
          repository: redis
          tag: "8"
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 48Mi
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - redis-cli
                  - ping
              failureThreshold: 3
              periodSeconds: 30
              timeoutSeconds: 5
          readiness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - redis-cli
                  - ping
              failureThreshold: 3
              periodSeconds: 10
              timeoutSeconds: 3
configMaps:
  config:
    enabled: true
    data:
      config.yml: |
        upstreams:
          groups:
            default:
              - 192.168.2.1
              - 1.1.1.1
              - 8.8.8.8

        blocking:
          blockType: nxDomain
          denylists:
            ads:
              - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
              - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/refs/heads/master/youtubelist.txt
              - https://perflyst.github.io/PiHoleBlocklist/SmartTV.txt
          allowlists:
            ads:
              - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
              - https://raw.githubusercontent.com/m0zgen/dns-hole/master/regex/common-wl.txt
          clientGroupsBlock:
            default:
              - ads

        caching:
          cacheTimeNegative: 1m

        filtering:
          queryTypes:
            - AAAA

        customDNS:
          customTTL: 1h
          mapping:
            homelab: 192.168.2.18

        clientLookup:
          upstream: 192.168.2.1

        ports:
          dns: 53
          http: 4000

        bootstrapDns: 1.1.1.1

        prometheus:
          enable: true
          path: /metrics

        redis:
          address: blocky-redis:6379

        queryLog:
          type: postgresql
          logRetentionDays: 30
          target: postgres://cnpg-pooler-rw.cnpg-cluster.svc:5432/blockydb
service:
  svc:
    controller: blocky
    type: LoadBalancer
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv4
      - IPv6
    externalTrafficPolicy: Local
    ports:
      prometheus:
        port: 4000
      dns-tcp:
        port: 53
        protocol: TCP
      dns-udp:
        port: 53
        protocol: UDP
  ui:
    controller: ui
    ports:
      http:
        port: 3000
  redis:
    controller: redis
    ports:
      redis:
        port: 6379
ingress:
  ui:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      gethomepage.dev/description: DNS Filtering
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Apps
      gethomepage.dev/icon: blocky.png
      gethomepage.dev/name: Blocky
      gethomepage.dev/app: blocky
      gethomepage.dev/pod-selector: ""
    hosts:
      - host: blocky.homelab
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: ui
              port: http
persistence:
  config:
    type: configMap
    identifier: config
    advancedMounts:
      blocky:
        app:
          - path: /app/config.yml
            subPath: config.yml
            readOnly: true
