apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobooks-iscsi
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: iscsi.csi.k8s.io
    fsType: ext4
    volumeHandle: jellyfin-audiobooks-iscsi
    volumeAttributes:
      targetPortal: 192.168.2.178:3260
      portals: "[]"
      iqn: iqn.2013-03.com.wdc:homenas:audiobooks
      lun: "0"
      iscsiInterface: "default"
      discoveryCHAPAuth: "true"
      sessionCHAPAuth: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks-iscsi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: audiobooks-iscsi
  storageClassName: manual
