apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
labels:
  - includeSelectors: true
    pairs:
      app: jellyfin
      app.kubernetes.io/part-of: jellyfin
resources:
  - namespace.yaml
  - jellyfin-folder.yaml
  - data-migrator.yaml
  - webserver-deployment.yaml
  - webserver-service.yaml
  - ingress.yaml
