controllers:
  webserver:
    type: deployment
    strategy: Recreate
    containers:
      app:
        image:
          repository: jellyfin/jellyfin
          tag: 10.11.10
        resources:
          requests:
            gpu.intel.com/i915: 1
            cpu: 1
            memory: 1Gi
          limits:
            gpu.intel.com/i915: 1
            memory: 4Gi
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: 8096
              failureThreshold: 3
              periodSeconds: 30
              timeoutSeconds: 10
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: 8096
              failureThreshold: 3
              periodSeconds: 10
              timeoutSeconds: 3
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: 8096
              failureThreshold: 60
              periodSeconds: 5
              timeoutSeconds: 3
service:
  webserver:
    controller: webserver
    ports:
      http:
        port: 8096
  dlna:
    controller: webserver
    type: LoadBalancer
    ports:
      dlna:
        port: 1900
      http:
        port: 8096
ingress:
  webserver:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      gethomepage.dev/description: Music & Video
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Apps
      gethomepage.dev/icon: jellyfin.png
      gethomepage.dev/name: Jellyfin
      gethomepage.dev/app: webserver
      gethomepage.dev/pod-selector: ""
    hosts:
      - host: jellyfin.homelab
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: webserver
              port: http
persistence:
  jellyfin-data:
    existingClaim: jellyfin-data
    globalMounts:
      - path: /config
        subPath: config
      - path: /cache
        subPath: cache
  audiobooks:
    type: nfs
    server: 192.168.2.146
    path: /mnt/Personal/Audiobooks
    globalMounts:
      - path: /audiobooks
  fotos:
    type: nfs
    server: 192.168.2.146
    path: /mnt/Personal/Fotos
    globalMounts:
      - path: /fotos
  music:
    type: nfs
    server: 192.168.2.146
    path: /mnt/Personal/Musik
    globalMounts:
      - path: /music
  videos:
    type: nfs
    server: 192.168.2.146
    path: /mnt/Personal/Videos
    globalMounts:
      - path: /videos
  dri:
    type: hostPath
    hostPath: /dev/dri
    globalMounts:
      - path: /dev/dri
