apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backups
spec:
  cron: "4 3 * * *"  # daily at 03:04
  task: "backup"
  groups:
    - default
  retain: 7
  concurrency: 2
  labels:
    kind: daily
