---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: 1.11.0
  interval: 5m0s
  values:
    defaultBackupStore:
      backupTarget: "s3://longhorn-backups@eu-west-1/"
      backupTargetCredentialSecret: longhorn-minio-secret
    persistence:
      defaultClassReplicaCount: 3
    ingress:
      enabled: true
      host: longhorn.homelab
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
        gethomepage.dev/description: HA Storage
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/icon: longhorn.png
        gethomepage.dev/name: Longhorn
        gethomepage.dev/app: longhorn-frontend
        gethomepage.dev/pod-selector: ""
