apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - namespace.yaml
  - sealed-longhorn-minio-secret.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - nuc-disk-config.yaml
  - ingress.yaml
