apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
sortOptions:
  order: fifo
resources:
  - namespace.yaml
  - longhorn-minio-secret.sops.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - ingress.yaml
