apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sN58r39SlvWxLC+2QA5Ro1EO/o3l4+OYookAaw==,iv:hC+n1CobylDofgmzmlZSRAYb0JBpTV2DArYfN5njZQY=,tag:ubJ9GGwEOm24HPNlCV8jkg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:9OCw7ozLXLtmNq0l8JZldikk79JGuNTdzTqEmRq2Vm4=,iv:Vr79IBFORXZxI3II2Ym40ZQal1KtDJHoNFBluoWwb6k=,tag:Te04HswyhLW5kwKiaFeekA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pAh1eXzBof5X8VqkrfoLZoJxJvZGu0IXohcW/QpDmC/8SYI5SsBFHOp/r8z92F7Ar5GbB6lQZxE=,iv:JcWoSpsPTFb+S1smgSWUrKfey7tBENfFs/LSC4t3/Mo=,tag:nBpjPQRUWl7WxX+8PJBmig==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: longhorn-minio-secret
    namespace: longhorn-system
type: Opaque
sops:
    age:
        - recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYk8zSWdhZ1NUcjg2c3BK
            TERuT3hNZi9iZ3pHV3lHeUhCc1lCRm12aHhZCllJQkZ0RzZidWZVaG80clRXMDJI
            Ull5NUxCWkJKK3BvNDZPc1lmaUVJNG8KLS0tIGIrT2tQczhhbnM4MjB1TmFaRTRL
            OWI3UldxT0k5OEpuQ0MvMWpnczhRN2sK+4Ffo9CfS32AG1IlkZbVciDWOUdwG0dr
            Hjlg+70pEl8crjoABM1iPtaqsWKx+0ZPiARI+lky4ADaIoXvwfEx5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T18:38:18Z"
    mac: ENC[AES256_GCM,data:kspqmVjEVxHWbgmxuvHlH8ziwT8lro+OkbBrGjI47ediEpUerWIeIfwbrB3zYOfOP6EdjaVim3tZH6jz5JxaF4ErORHDvQwX3wfishGvCCyMJQvNAAOlKvPDn+7j2438if9OgtbJjUxG95ykftNmfxT0ohvEidCk0FDimtROG1w=,iv:MH3kSFKKuJianQaZ2gtNux7mLlTlvMVydmuljMSUB9M=,tag:n58TmbjN8fvBi1krKG4B9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
