apiVersion: v1
kind: Secret
metadata:
    name: longhorn-garage-secret
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/3U8Ec5uqUbMnY7ziUp6YC7i/Biw4ZvUPR1XLvHunr0gjQ==,iv:8JIZ17V759VbKoBH6laG+eXLoKno+9IHIbyChqDIryE=,tag:E8LgiVA9xJJqdiPYJCPVtA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/ZJfudLurSm3SMfNYN8ln8sbFeGE1fo3R01Zuq/0cM+0GYX6svuBsko+3ri094tu39l3yTfvVnQk1DP064aagQ==,iv:SufEKzrROFc4Sb5YDWOty+0E26tlTa76kOMr21QuCwk=,tag:+FNM0NoV2R08E8GboVSxlw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:uoSQlcqsZxTdlx7NXRFh0V3GNhQ5vkr9DWzu+nS0Zw0o,iv:PSNAch1KmMh2VrJZTReA9i7KX/Y7ViJZ+0EpKRD3U1g=,tag:3e58h6MMc7gV/5tBVBIaew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aGVGS0xLemJWRFh1NFJa
            L3R1dG1YU09ORkZ6b0JZNjg1SGhPVzJUMGt3CkFOK21ncmNqUzJPMCtZc2Y5NDBv
            c0owZkJaVVdYU2FnY0RueTRybzRDUWcKLS0tIHFmR0VpcnI2cElGOHBURmNaVmNL
            d3lETmp3VTFTR1duNTJqRDBNNFZxb0EKcGb+uunAM18/7Wf5aeXny/hYaX9+qU6A
            6H6qWO+qbkwe3EtlTRpxUbI4uQ9yGwmUeJb0erjwfmeHAjdPzNrVGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T19:08:16Z"
    mac: ENC[AES256_GCM,data:Y1xpr+V2dNPtvKc9WjVuCfUPScNuFQxoB/hF3HTdNJI412tYeo2+jDKkUAXBXV8I7w5ZknMEe3x54PyC0DjejXOuzjdcwbrk6DCk2JgbVlvywkFciTG70T6yVGL+qxkxT6ugCSY4kmrlZmt3AMt9hBO/eTpebLcjIJ3TyeNP9BA=,iv:RsSi6Kc8dsEJkuSOtZVi+U6AUL7UNhgNrP0hYSACTzI=,tag:p9bqOWvXn5OnQhNiXtbxUA==,type:str]
    version: 3.13.3
