apiVersion: v1
kind: Secret
metadata:
    name: longhorn-garage-secret
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/3U8Ec5uqUbMnY7ziUp6YC7i/Biw4ZvUPR1XLvHunr0gjQ==,iv:8JIZ17V759VbKoBH6laG+eXLoKno+9IHIbyChqDIryE=,tag:E8LgiVA9xJJqdiPYJCPVtA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:D5+jOe+GFvDb4a9cC3iNv4rG3qwI0BIwy7uVoWIk36swvcKsmA7ktgxpZJvIUtBr5KBX/8OBxXWUt7L1+SzfDw==,iv:ZtjdFQfhTzzhlT+8CiJnz2WKNy35il/VBPXNENcWGB8=,tag:43UqKswJr+zilJzwGnsIdA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:QGxw1FW/iVcMHCcym0e984fjop3clnf4Tw==,iv:gu5lxGiYkVq/K2ewPwLyZjH9zTj9g4Vs37WyqY3Owco=,tag:DroxZBS2CPiNkuS879jCBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aGVGS0xLemJWRFh1NFJa
            L3R1dG1YU09ORkZ6b0JZNjg1SGhPVzJUMGt3CkFOK21ncmNqUzJPMCtZc2Y5NDBv
            c0owZkJaVVdYU2FnY0RueTRybzRDUWcKLS0tIHFmR0VpcnI2cElGOHBURmNaVmNL
            d3lETmp3VTFTR1duNTJqRDBNNFZxb0EKcGb+uunAM18/7Wf5aeXny/hYaX9+qU6A
            6H6qWO+qbkwe3EtlTRpxUbI4uQ9yGwmUeJb0erjwfmeHAjdPzNrVGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T13:54:45Z"
    mac: ENC[AES256_GCM,data:WAEfTQ5wF6+jHLiJhYygXvfg637c92pV2ICkVYNVES8mMTEtGJKTksGjxdFZaJvmNhY06iE9P1KNRaiXCOlmjonYllU2pYyL78BVlp4z51hgqp1USkUF5BxpdkNOfU7HHhAMeVauXmgwOav++OPYZBKrhAFMfpbt7x+XXh/1vgs=,iv:IyFAUVR2afptWl42KLZ0X2EdPyMxw4S2cgo2MMW0FWY=,tag:wj2M17SJMqkZQCje+uefwg==,type:str]
    version: 3.13.3
