---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nuc
  namespace: longhorn-system
spec:
  disks:
    home-storage:
      path: /home/longhorn
      allowScheduling: true
      storageReserved: 40960
      tags:
        - ssd
        - storage
        - fast
