apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:yfuiHycjEAS26TbuOn1HxWJnZKBwyOK5O82f+StVaFHgWp3Xc7sPw8DXOPwyt2ZgZgIDJULkOWGmFI1k+eky9i48I3ZTDzxAOpzfGQ4zxr0=,iv:+9LWrwHJk3YmTc69xtnKg7bbJWw/kOcA1nCvcCtM1/A=,tag:F5E8J5BVWfZ98IN0yyoTXQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:C9QOqi4I+LwDGYAGjFiOmLrKhuhBmP187PHCrlRENcsHIybC3iJP7XMgTfJtpyre,iv:KVz/Gwk1pf0E4mKwB73fvam4VXeQd+XgqT4aRqt8jBI=,tag:T4ym7pLfgOLmOxLqIDDNow==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:dAuT/x93Tpln8JEQ9ppzDF2UPmxtVrDzuJrFxx5lb2Q=,iv:+X9YTG9xCBTIrB1tj+BkMqfQkHaWJ3PiNfVbLThPUHQ=,tag:e/NRCnfDNSlcUKxVS2mgtA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:QozpxsL8xIgmj9qcVcEuhRMERSh8pW7DXv/Hub8iqODkt4az7OEnjfjYuxhKPrEfq14crdxKj3FymyCPSJfhMg==,iv:licSFr1QSwBpQ5elOb7C6Gq3wil4LWhtaTRbI3fOlr0=,tag:s+JrX6Di4vEbYiq0zDNt5g==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:p9FlqtAhMlCC9jXkWfDnJyCN6IfmVJkQ2TVi,iv:X11ALoopdpJriUCwr++43/yX93enDLBo9kTg+pch0gY=,tag:elh0SM5MWbwCdAi/kMFs4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVXEvM0dwZnU0VmJsZXRo
            aE1IZGZxL3RrTFZRSWY2cFZzRkFneXJsYUU0CnhENzFqWnlvcUswc25nekZIdkZz
            cEZjMGZvTEhUZG1Ya0ZjNlNYQXRpL00KLS0tIGYxQmJaK0xseW5MdTlXajlYOEtL
            QUxsQ2JMdnlJWk1kUmxhaGcyT1dPUTgKhjiiOoQhZaI+zZZDU3DVjRe+MSIYok7U
            BWJDZMhu20g9CZe0rHW5zvsHNFx1g04pErlQNNz9F5sxNXFh3SfD8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T15:16:24Z"
    mac: ENC[AES256_GCM,data:EoPJAViZ9L+DYq+EWMFQxlr9w+VfYVRfyG6egYuQpYeg+okJoine0eTyohI5qeF4Qeg8XQ0Yp9eIwFzut4n14pptxRQDFLeGndF2hK0ZhjlnPCtrz+5Av+CDR5IT0ua13EXQjBkmwj+Bm2ccUlQiyGl7oItbHf24gISnbsRZMAY=,iv:VxYSjcWJFL8g/AsOkQcDNHLK4V1P97whuI1XzpENRfU=,tag:hM1CORRIBul2bpPXmcN5sA==,type:str]
    version: 3.13.1
