apiVersion: v1
kind: Secret
metadata:
    name: authentik-oidc-credentials
    namespace: authentik
type: Opaque
stringData:
    GRAFANA_CLIENT_ID: ENC[AES256_GCM,data:H5y/kEi+QUH/ISeRscI2/G+OiPr1Gr/Mbxiyh1x+HF1Ws6DkYYB1bw==,iv:oZF/Iz+zFcEQ4sK0Ow0iKArcpvb20cPPWvtmxxSyLD0=,tag:G2N7EYmNxpkRgFtdIaFJVw==,type:str]
    GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:Fhv6/lUgpa8vzsCPL2mLVeamt2al2zW46qYiZy90xsuieeqXd8n8ksXHT5XcC/EGpFUx7S/0x39Ck01EenF+SYiwa2WBNcx8xqPEIbvMhwPkQniFaSFu/XI4515LNhzEVcgc9KcnpufrMmXL3gcmeCcezdGYlHnc5Sou3KI2vAQ=,iv:Cq8zehwwjMAboabFv7QFgoBQQT8tau2/FdGrx3uNUsI=,tag:ozIYgKGLkJBjCsv/Gq2efQ==,type:str]
    MEALIE_CLIENT_ID: ENC[AES256_GCM,data:44As9xR3/bNj63uIZR7L/+NRfp+S3PpfC5IKrXQ2VsCusIkuBiZJ5Q==,iv:jlggJavClHsXIp3RNX2c2opr1WSzO+xEkKz3bV327d0=,tag:uFMYmOjeV8iGnKXbVdhKog==,type:str]
    MEALIE_CLIENT_SECRET: ENC[AES256_GCM,data:ETsAySZq1VpY5XnY7Ewi21SGvIJtsRu5Qc1LDMz2IIFmxo4udOgwTBM1Hb69BkfKxXPfJ+k7uEkb+pBa9qckwo/RszBZg69aZ8sca9EjM0hkWKnejoyHQ4KoDdBMnNF3MmypFSDgYy1p4UVy2wjEp1iGoouvqqMXzzkq+N8Bvrw=,iv:V/qenCVwaZzsFnW6DLjKsjhkXZZU4INJqcsvTFJTZSk=,tag:KyMaVTq5EA2GP/A5YMzKfQ==,type:str]
    IMMICH_CLIENT_ID: ENC[AES256_GCM,data:3QfiGVohOX9UBXdMzbs3X+s9AdAaOBj1oVvmhmcuF/tBTCSfIQSo/g==,iv:VBFhuj7f6u7RB+/NREwVg4Ek2dNF+HKXzPU0wEGsJzI=,tag:wocd+05Y4cyMi4Wbzc8s/w==,type:str]
    IMMICH_CLIENT_SECRET: ENC[AES256_GCM,data:m4odqgHSIFdoj9EcDNV6VZFiCScZAex9H+mVxaS2qKeVD9FVquonYKjby1W5D9XU/AyrgjME/Oq+tZPL/RN6c3fBI1oEIOpi4nSbHFVWE4k8BN5MSX0gaLR2Q5b0mARaXnHd/wiY9tsudoEqwWIx2yiEOYbID906WThBz03j5Gs=,iv:6A2/7bwvq3WrtoF7GCFa1u8/jAD4crmOu9p9mOQtwDk=,tag:GID/3vHiSZnjcvqMbWCimA==,type:str]
    JELLYFIN_CLIENT_ID: ENC[AES256_GCM,data:a9SnOROjNJUhd+UXT7qc0bJ+hT0XS//39/X6vcyOtIJzPhqtkSyPzA==,iv:G9CdTnsLY9Y2lCqH/GCExxzE7LetW3wFhEMuF1Zx624=,tag:Hr4CwHnJys5Pihz22nlO3g==,type:str]
    JELLYFIN_CLIENT_SECRET: ENC[AES256_GCM,data:hOKRJfCBRmyz4//RM7rY2CaBkn85n4XEV0PSVURVFp/NbZzUmksyXJaCirs4FtgY/105lxESN31ZI7h1HPj3KnricET3Afa9McGe08gIXnFkV8ABZfwGB2ApZrs3NxNKZPtia9g2qOHfSp/VFED6R9/ADZPPh+2gzzPkXevqquI=,iv:d+5lmiiw39HC6qQQ0y+Fpb3wVcphnxr2905lb4kqSig=,tag:w6+07ILmVfdGOeazG7Hozw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZDVuYXNENkpTRVFmdnNU
            WE00T0UvbW5rWGdoS2hPaU9pV0JDdXFnY3djCk5YRXBTa2hGWS9WdGg3TXE4OGpp
            Z2ZvS1dGcUVPYXVVU203WDc3bi9UNnMKLS0tIGpXaW83clVJL1FoNmtnUGNjV3Bl
            OGhpc2hkaHlhbWJSL1NxNFFvZU9pd1UKjO1qNp+9VeEXlziHZRMIaqK+yjilUHVe
            gz6QQ1KJBoQgVL2cu5Ov5pmT+wZ32Oargt4KEMb1RSrMwBqji+KnkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T15:27:20Z"
    mac: ENC[AES256_GCM,data:+40g68u9Er11dO8w7dCKKRXH7qANV6jbFDopANsxUMaDd8ZFjdIETSTGw5B3igSfxMdAPmIjdlbAspKE/WkAYA4nUbYK3fjYJ+XcCUYU3QlXoWRAnfeac10YZ2f5U3JdYiwsKpB86dDeM3P+ogFiKEpKF5DOvrbTzqDsghIPmbo=,iv:srpFCeAGs2sSv78Hytfht3WvIhG+VXJSg39nWPlPcMQ=,tag:pg4HaKhs1U+ramjerdqW7A==,type:str]
    version: 3.13.1
