apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:piWNfnRFp5GOIRbOHE6xAHpj2cCjvuXwY1UVLzHzRB1usZE811QN1JOvRKYiV2amAJkvcoFDd408GeTtcvo9CC8EikI4j8z+TDtAmlVBfmw=,iv:4oVoHjjfmR12jStapjwKULNeYNU6skxzp8CjBuRJFQg=,tag:4FpkPd++lhgWUXrahbcJHg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:9Pt4ttS8BOkB9/+8WnfSutiqqzeAmTQrt7f5rsx2Kg58REU81k/Ghg==,iv:W/r0O/UgwOz0I4XkRqnHDrPh1uhEnU2KzPt4LJhVS7k=,tag:x3qup6huo2Ja+Kp+tF7HhQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:gkL0ud+Bl3dVpmrNRrAdMc0G6wK8juMw06kySk0e,iv:mC1E5hrwwYcI7xPWpag2zpEOeWcYmgemFXaxKetOj7s=,tag:0WjYAfYBFHVF3WUqxTfvQQ==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:v5UMkALVfPpCuK7kKkC30rvU0yv8yO7wVJyFeRpUYLyGVJD/b7uqLDmWVTa9NGwRlb4E3lQo93RpWVpn,iv:ug7P96GZUkTBN8dfR03fIw9VLFRzQUJ/EsjDk7z6YCo=,tag:8dNfc2AqNX6h8aXwnyv5cg==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:p9FlqtAhMlCC9jXkWfDnJyCN6IfmVJkQ2TVi,iv:X11ALoopdpJriUCwr++43/yX93enDLBo9kTg+pch0gY=,tag:elh0SM5MWbwCdAi/kMFs4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVXEvM0dwZnU0VmJsZXRo
            aE1IZGZxL3RrTFZRSWY2cFZzRkFneXJsYUU0CnhENzFqWnlvcUswc25nekZIdkZz
            cEZjMGZvTEhUZG1Ya0ZjNlNYQXRpL00KLS0tIGYxQmJaK0xseW5MdTlXajlYOEtL
            QUxsQ2JMdnlJWk1kUmxhaGcyT1dPUTgKhjiiOoQhZaI+zZZDU3DVjRe+MSIYok7U
            BWJDZMhu20g9CZe0rHW5zvsHNFx1g04pErlQNNz9F5sxNXFh3SfD8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T19:52:04Z"
    mac: ENC[AES256_GCM,data:nY+barrgBTQTz+fZWF+r58awHouzh+GauLQiUSeYct6Y8SLZPuK98+wxN16PGYNjcrXoh90kCyXdzIpRbmBWIJ7PyRxJo2m7ZKNjY8Ist9VxgW4XMZqubXKQ0QtzFDoiJ2S+sfOmXGGiE13m9638CSqMWJ5swEUjw3euOvvbbLg=,iv:pi5SUBJsPKTqsH5U3XL1rU+X2cCDNq5rJI+1LxV6awQ=,tag:qq+GGbiw0CLt/ELQ+QTM4w==,type:str]
    version: 3.13.1
