apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-secret
    namespace: paperless
data:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:7qmB+GvoW8evmb4z/vpDKZtQLSLuG+ehJyfy5Q==,iv:O8euJRcvrM4/hafSknufrt/P5Z4u3IL5M4GzugP7ISM=,tag:K/O+creeAN/FrLZldwIrxw==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:4xAvhsKZyje7w1PX,iv:iOJwUQiHiV85qtJIfZUgjg6aMwOENCVPi3UiBgHrnok=,tag:gCx3zSYNevL7gOlgR8kA3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMGVoUWhGcGNaeGw1VXBM
            UUxFRVlUTGhzc3ZUT3lDQTZsRjh2cGV5TVdzCi9nUExuS1hsakY4TEpqWEgxb1Bq
            VFM3TkJUeldmRTh3em1aUXJXU28yT3MKLS0tIGd4L1UvMlpTb3F5VXJlZVdxSTlX
            UEhHbnBXTC9Ba1l5elVkUXV0WWJQMTQKmEXfRLep79aqtpltegdNayiw2GiQpZwt
            mjGRJrzyCEjWeoiW4pObcNJwFSbiMTbBL05mwphy2UOmsAR//HJXUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T22:57:33Z"
    mac: ENC[AES256_GCM,data:g0x1WUvoX6W1nPdrkN5jjBQAnXIyImm6Fg48xS0f7vw+sMe06IFSGTYIUs0ovcCeplhWo+9rD+0Tt/Uv0lh2USfw0MGGqZwSIA+5ih19CYrRgj4lT1yIZ/EJLdZXGMRyBry2CB6WxVkJ0DPUhgXYiszDS3svHgOf4Pr76LYX7jc=,iv:5cSIHszc6BMsa6yTXj3GDdd92tJfFCrRqugWIq8mzKU=,tag:tAZmo6E9x70eGHBezlY4YQ==,type:str]
    version: 3.13.0
