apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
commonLabels:
  app: paperless
  app.kubernetes.io/part-of: paperless
resources:
  - namespace.yaml
  - redis-deployment.yaml
  - redis-service.yaml
