apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
labels:
  - includeSelectors: true
    pairs:
      app: paperless
      app.kubernetes.io/part-of: paperless
configMapGenerator:
  - name: settings
    envs:
      - paperless.env
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - db-secret.sops.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - paperless-folder.yaml
  - webserver-deployment.yaml
  - webserver-service.yaml
  - ingress.yaml
