apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
commonLabels:
  app: paperless
  app.kubernetes.io/part-of: paperless
configMapGenerator:
  - name: settings
    envs:
      - paperless.env
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - consume-pv.yaml
  - data-pv.yaml
  - export-pv.yaml
  - media-pv.yaml
  - consume-pvc.yaml
  - data-pvc.yaml
  - export-pvc.yaml
  - media-pvc.yaml
  - webserver-deployment.yaml
  - webserver-service.yaml
  - ingress.yaml
