apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc-secret
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:7M5A87eWk836qNrl/C+24hjvA+D+Hyd2vq0/nurWikwuiX4j/R90I8uC4ul/koXHNSB0M2eeKVMLGY+oveTEiTgjpozayT3N6EPdBMhLCSqQjcjJnLf1YkPdXAovv60+G3dns9XmbR8EdYvGKMk8KAtv8En+qbG7YUYT8UuWe610m3YhNiIH0cAYTJSy5/4/nXH6WVcdQpNJKoJwEDOo5mrS4DfjRtQyYF78n4TamA/U3t/bDLjq7Y8jwj6Edpuu+77md/jpfDPLbmkyIEcyIknBIEeCUJPVCZViqqAX/BcuYRQ4F6fqXiLCTXYkx4DWIgtReoHT4kxSxgqR6lnvlfA4jYdMXLdtcc89fGmbAn1Oe+OzSWLxZ8FIbMChbI7gm4iKRqPcgaSq25PekC2lOpvOVQV00d8EHg5sN1A5slbc/o9HrMnmHOkODKzp8wCyWodtZisnQZ4DZmU2p/9DK4aFmtBJUADcsQuVSaVKwZk7ikNXBrerpj36gKOpuKw78HAj6HI2PyoghCWUHCPZfZTk/hZwegE9bkr8IcX3670FzqXyff9M+LvuLwAAgjbT4xZp2z+joF+lpqPLYeO8f7yYlAHiwhXyK1FputaJkXqNCo4jm7TlA8NpviGY8A==,iv:SZ/nu1cohfZlyxF038buPh8C4beAc3LEmSjPhSPVfPU=,tag:OWu1MkOUKo6OM8li1+IFVw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:x72ywb4q2QWwhpEKHxxBBGIo7e9ywIzaMVVkf59HFs73M2HxXiQYwiRKmHJmBnx/W/YRUi6FBLgTvVl/1dF/TI+2ndWmHAywpBOyIAmf3BkmJCgoD1Q=,iv:10KfxdjbC7EgboYu1xhYG47H1QBSyjBLK2NoSR/MwCg=,tag:KavWMwJwFrE8NVE4VwZcNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ0hLSU5WU1huclB5MnlW
            aCt0YVZ3cEVzeUtNWnJ6ZEtQVU1OTkdRd1FrClJ4NmIyMFR3RGVZeFZCRk5DZTFP
            UnVGVmdoV0ZENUN0ZTduZzhvSjJyRXMKLS0tIEo2RHhJNDkyV0liV003eUNlWW5t
            U3pJaDFtS0xPSEx2d3l4b0FsL2xWSFEKhKEFm40EHZbmciQ5ROxeVFHD+39l7P+O
            o4qWNMm3jsTToo7WPDGd02RDQf6tzROWatmsKBVJeQHuJaxpusXVoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T19:20:40Z"
    mac: ENC[AES256_GCM,data:svbi6Z3h+xWAJH/0Yj5ZE9xHvPVrzuEGwuEp1TsacirItgB1rQPN+JE6moQtbMRGt1N1XM2ohggULu5n8XVl1FfykSkJkZRNOkUPwrn+b5Q0u66liyPLQc3zFBML97fZnwLSnir6Q8euK58Xj1AEX+6wweQMlWmDsOiPmbnKw7c=,iv:Yp9oR6S6F0ctP/PxE0Li3gjnJ+Q93G4m2/QOjXqXyaY=,tag:GsfMbHHcBMWo2jJNAB5j/g==,type:str]
    version: 3.13.2
