apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webserver
    spec:
      containers:
        - name: webserver
          envFrom:
            - configMapRef:
                name: settings
          image: ghcr.io/paperless-ngx/paperless-ngx:2.16.2
          livenessProbe:
            exec:
              command:
                - curl
                - -fsS
                - --max-time
                - '2'
                - http://localhost:8000
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
