apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: ClusterIP
  ports:
    - name: webserver
      port: 8000
      targetPort: webserver-port
  selector:
    app.kubernetes.io/name: webserver
