apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - github.com/metallb/metallb/config/native?ref=v0.15.2
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --ignore-exclude-lb
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: speaker
      namespace: metallb-system
