apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars
    namespace: flux-system
type: Opaque
stringData:
    LOCAL_DOMAIN: ENC[AES256_GCM,data:ZTiiRSJ/Pg==,iv:LJl5qVrmktYpf1CBSs0UimwJvhoM5wbEqVJn7aKaIj0=,tag:t0YUNYiRPuIyIQHKi2hppg==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:numbHMvfz3Yn3P8WvRm42Aqp/axYDA==,iv:gDEnYfWTSOIeIusyfDw5vjEiNYwEMQExiKTFoOJHtNc=,tag:xrcpVL/UdcZeRK/7F475YQ==,type:str]
    NAS_IP: ENC[AES256_GCM,data:+C5u2BbrjJv8aeFZLA==,iv:9oedBq3nHoTOlPUKgSSMfV4VjUmFtB1IEuhb7OZ+icw=,tag:/b6e9rSkH2tJGVGT7/6pPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMUlsZUFXT1dTTXZsQjVp
            aUZBMUN1TkVMczFDK1hHalNWTnVZRzBUbTFFCnFzNC9zWnN3eWRjME9CbWlucklv
            WFRwYktZd2R0R043c1NweXhlYzFvNDQKLS0tIFpQR1EvWnV3QmtGWDgvVUx4OEY4
            TjZOOWlCUVVjcU9hWlgyRVRseUE2TlEK3oFMnPRkTY7eS3LNIy/O8BH5Je5CsNDw
            kUAWCzfYEVFYUs+aFt8oofYlvcjjqR5GZXflzSUzwjHPIyedmqxb/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T09:56:30Z"
    mac: ENC[AES256_GCM,data:ZSLnbzBO+xh6V7Ec1bXhrcuZYlGgkNwGlksihYD/kuuzCBpyZjMHh1InTdNCnHuLBIhqKS0cmX6dsdMIzhQXvBI7v6kdaIzMO3msQTIsi559F54/nQRe1WrFweuWpEFsE51x4rLiAkFLZPlH5WYUXCWRLMWUbrC0GRfCIAMZTFY=,iv:avw+845ymT5tYkRzOqGHLm1fz4pE7d81c/SzR/N3T9U=,tag:VG1HWZIw8BEpOppg2LpN9A==,type:str]
    version: 3.13.1
