apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:Q9vMx2q35pWiX3PM1jltboDmsig=,iv:/HtzRvMbS6YrjSBftjyvin0NXBmcjpHxqCIeJ2meqSY=,tag:Q6NV9oG/h3KgsKlq646aLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaElzeVkrd2JFUUJqeU5o
            OEttTlpPc2NnNzdlenNDQ0JQVlBudHowVlJzCkc4NkFlRWQ0TGdNM1ZoS2g3bGVv
            dVlQS21TWXNrRkZERHdBTTEzVWVjTzAKLS0tIHdId25WNG5NdkhYdnR3c0ZMN21w
            eDZGamVPWkd0L0VNeDYzWUdVZ29TejAKEK1ZGPTqMGgilaqXcutBcfkVXFzV192H
            2ybbl6PVZvgEtirLKEDLTVzMSQKmrMGsZE68U/Pc6rxmGyFOh8PSIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T07:36:21Z"
    mac: ENC[AES256_GCM,data:MweSRD0Gc8gUICyip6xgW85p2+JKcDGYmVwG6+je70Jyrj7hmO7N9UryVIZCjtXrEJJXcZejBApGvlwGgVS+hcCeWV1OO7pbdOc92d22rkvov+I910Tk0pWb57J65SubsYUpij80xPveIVkTw3EjvErzgnkSy3gvfh1JvS3TkiQ=,iv:SBY+ChkdXAnFcnNzOBXjF+wYCXjGDKxnNuyofyRVGdo=,tag:9Yx4RTP9G09yMrDJ5ptaJQ==,type:str]
    version: 3.13.1
