apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      version: "40.2.0"
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    additionalArguments:
      - --entrypoints.websecure.http.middlewares=traefik-lan-only@kubernetescrd
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              priority: 10
              permanent: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-external-tls
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.homelab`) || Host(`traefik.${EXTERNAL_DOMAIN}`)
        entryPoints:
          - websecure
        tls: {}
    service:
      annotations:
        metallb.io/address-pool: ingress-pool
      spec:
        type: LoadBalancer
        ipFamilyPolicy: PreferDualStack
        externalTrafficPolicy: Local
