apiVersion: v1
data:
    password: ENC[AES256_GCM,data:8GTCZNqHt6g0Nqzu/wbDq4gg7j85KoQk2qm9Cg==,iv:XPwzBkzMEvxO6jDz3dLHx06kJWhav8P5wKghpmNPuOI=,tag:ctKBWZME+bUJ0Sf/4stciw==,type:str]
    username: ENC[AES256_GCM,data:kSIjdn5aLKY=,iv:AWEwdcBD6lsSt/7QwH/9BBZVsHhmiIwo1lqLiz7cyg4=,tag:Ak2bXj0vCgMEHKwrMCpycQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: db-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcTVYK0VzWnBFL1g3SXVp
            eUNsa0RxcFhwS2pnWkY1TURHRzU4S1E5VGxNCmVmczh5Q2U5T3BmNGlNOFFRWnk0
            TDBGZ3Q5U3k0OUF4SUNJeWFYVHpWOW8KLS0tIDUrOXlCQ0FYTmhRd1RFZTFDU3Rq
            U0Z6QXhZSisxenN4UHBQT1MxemRxbFkKcVCqjAmE/4iWrAWSOxEKvURRgqKPUWwB
            rrTzsn39gUuacJLSuJMObXhuKr9QDie0ry3j8vz2wM/62SB1d6qeRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:57:10Z"
    mac: ENC[AES256_GCM,data:4wJhaSTszbdaOWAukEwH1gAq2ngewaQkIishnrfaik5du13WXeILWFWMpC7UU0gXNwD/wPdkR5pleprDlHdVfI8eVqfdJH19XZ/g81mqkHN7nAdKoFjJ/xvvZ9hLN8dMp3LljK7gwbuSqzCLuBhsj+nKAbfSCVLinUDlagbUVSU=,iv:Yh1+Z0XoM50iyUHZ7OgLWQwNLy/qucgExW7Shr1sDSI=,tag:V+mkYdqvsJN/r72gZ5A/OQ==,type:str]
    version: 3.13.1
