apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:hdVKtFCT/NRr1uQRDvJEs7ome3inLPjd+6vBhY4ZJjrUqrBmo1C34XSONMiiLXpzH2C8BeqKWek5sKzmSGsLIf4ZE1wzewLdvzd0SPIpr5YYUzzQPtrqwd4t6YBMH1qhz8gRwUayHmut44JHdnTvwvaQKHBlGbNfN7vIbXnVKZHRvpRQPQdwYlWzGBHCY/wXhqPcYEOKspYj1lNtzOD7wb+lfnjSHUOZp8r0EW/Mhsiq2A6K/dNn6ByMVooOoC6pyjNP3JIS6+zvDzGUDVMULZH3DagTeJTN5mrvDvbNlZVz8x6izuJmFKDpFpc8sZIxRqCb0JcZGvY=,iv:ckWY8e079pz1gTDjzOoNHKbx1kBhv0q9tHMDbNbsQYk=,tag:xWSxag7In7TEfrYyfsDsIA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbnJvY2JTN2s3RHV0Y0wv
            WXkwbmtZNmUzNWZaSHhmK3hheWgvWVpLZ2hVCmp5Mnd4eFgwVVp3eUgwRjJ2aFly
            OFE5ZnpYakFTTW5PYWZ1K0EvQmJHT1UKLS0tIFR6U2FGUGh1Y3R4SlM1YkZ6a0o2
            RWxoZ1R0ei9oTEVEaEZPSXlDbFFndmsKT5J/i6DwClgefZiRQozoSq+UCAHbpFe9
            TzFuwVn5rrEisrKrCkxVVZtFVXYM/rSTc9msoMI5Y5hZOTfTRk9twA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T22:18:59Z"
    mac: ENC[AES256_GCM,data:8OSKtj/5PaZ5T6imbBt9TUxR79YQOF9meg6HvcQO7+o3Y2u91GZZ1L7tKNj96c+pZTCw/I8HnZyWcXefs/SW0wmsPxPUCLtG2ciIiOcyVh9zbLXY4ebbrsXd6u4OJI2q4YM/ceTZKWO7B+U/y+Kf93QEd2gZzjKMxQiPt0QDSs0=,iv:E0wmPsSm7D0lmqgE+/FDb83ZWCEyguJYvXjy2pTNSc8=,tag:0r5Taa0DlDW882IHGEo7vQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
