apiVersion: batch/v1
kind: CronJob
metadata:
  name: lcg-scraper
spec:
  # Every Monday at 3 AM
  schedule: "0 3 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: ghcr-pull-secret
          containers:
            - name: scraper
              image: ghcr.io/wavefrontset/lcgo-offers:3.0.1
              resources:
                requests:
                  cpu: 10m
                  memory: 64Mi
                limits:
                  cpu: 10m
                  memory: 128Mi
              command:
                - /scraper
                - scrape
                - --spider
                - /spiders/
                - --pipeline
                - /pipelines/default.yaml
              env:
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: password
                - name: DB_HOST
                  value: cnpg-cluster-rw.cnpg-cluster.svc
                - name: DB_PORT
                  value: "5432"
                - name: DB_DATABASE
                  value: scrapydb
                - name: FLARESOLVERR_URL
                  value: http://localhost:8191/v1
                - name: TZ
                  value: Europe/Berlin
              volumeMounts:
                - mountPath: /spiders
                  name: spiders
                - mountPath: /pipelines
                  name: pipelines
          restartPolicy: OnFailure
          volumes:
            - name: spiders
              nfs:
                server: ${NAS_IP}
                path: /mnt/Configs/scraper/spiders
            - name: pipelines
              nfs:
                server: ${NAS_IP}
                path: /mnt/Configs/scraper/pipelines
          initContainers:
            - name: flaresolverr
              image: ghcr.io/flaresolverr/flaresolverr:v3.5.0
              restartPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: info
                - name: TZ
                  value: Europe/Berlin
              ports:
                - containerPort: 8191
              startupProbe:
                tcpSocket:
                  port: 8191
                periodSeconds: 2
                failureThreshold: 30
              resources:
                requests:
                  cpu: 100m
                  memory: 384Mi
                limits:
                  cpu: 1000m
                  memory: 1Gi
      backoffLimit: 3
