apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tAatUldeBYaF77FmW5hxbZLwAfgWdgmlNUs9eg==,iv:uZEVqpe03iC5nAwlwU9t3HiQc1bi94skOjiaBXyH5jo=,tag:eRP5P4RgG5/Hf+BMBJmSpA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:EAyVv34bFCM=,iv:/diIAsgD4RUOeyOuBL6EDGbsyNJ6Tw8zoG0UnDakFz0=,tag:Cd26Zc3TONUMuk/LJ8oxyg==,type:str]
kind: Secret
metadata:
    name: db-secret
sops:
    age:
        - recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVUZLSVR6OFVDdStGeUk1
            QVhBZEpvYmx6OWNzenErQ3lIZDNMR1cxclR3CndSOWh5VUt5UVZZV2duekwxMEpm
            TkpsZXd2Q3pKajBmaVZPQVlBblU5ZEUKLS0tIGxrUUJNRUcvRFd6cllDb01PUllv
            ei9neXpXTzVLSHduYkNLamtFUytkVU0KIyC72rBd3o4Co6cxpW77NqWuku+jLKke
            69dxbNN2dk3eQW3rTPRHJKWIh8qMz7MJ/mfIqdO7HIsUWz/wIx4Ebg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T22:38:43Z"
    mac: ENC[AES256_GCM,data:0GpNf0J+UALE1hn1A0w/0hRKe/8YJvt4xDO/1T2LSScF5OpwxL2wKECHPH1/rDAhj3FlrFbah8FAyQ4b4ixpIGBj3O0wo3V10gS1Mn/elBOB5j1UHNLiFPMTJfjc5FRfEiFP3wfcmjY3ihOSeY5S/7wMdP9qhTdduWmvwshgTL4=,iv:GZP5oJqvYpXfkT/RG1tCR8zkkFJXrdxXXIdseXKhGS8=,tag:2to0WQUqhMPKPsKvl/O5hQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
