apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tAatUldeBYaF77FmW5hxbZLwAfgWdgmlNUs9eg==,iv:uZEVqpe03iC5nAwlwU9t3HiQc1bi94skOjiaBXyH5jo=,tag:eRP5P4RgG5/Hf+BMBJmSpA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:EAyVv34bFCM=,iv:/diIAsgD4RUOeyOuBL6EDGbsyNJ6Tw8zoG0UnDakFz0=,tag:Cd26Zc3TONUMuk/LJ8oxyg==,type:str]
kind: Secret
metadata:
    name: db-secret
    namespace: mealie
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVUZLSVR6OFVDdStGeUk1
            QVhBZEpvYmx6OWNzenErQ3lIZDNMR1cxclR3CndSOWh5VUt5UVZZV2duekwxMEpm
            TkpsZXd2Q3pKajBmaVZPQVlBblU5ZEUKLS0tIGxrUUJNRUcvRFd6cllDb01PUllv
            ei9neXpXTzVLSHduYkNLamtFUytkVU0KIyC72rBd3o4Co6cxpW77NqWuku+jLKke
            69dxbNN2dk3eQW3rTPRHJKWIh8qMz7MJ/mfIqdO7HIsUWz/wIx4Ebg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T22:40:27Z"
    mac: ENC[AES256_GCM,data:Exi0PGMGSuZgwS+YYSnVogLA1G8v0UhddYxy7CHdgEvSMgd1u+FGq17ztb4bBVbzpCo0rkr0+LN6kE4tMQP+1mLB9+pnqznE2DVeuKliq+CpLouILuveOTKbqTvRQo9oN7V74+InkK2z5AdibfS/4bhajJIg2kDR91h7EcayJjw=,iv:XGwo7ijLgndtoAfF99Wo8Sc85l+bTVHouBfV2H8okVM=,tag:b4bezLiMTkfkfXa793+rtQ==,type:str]
    version: 3.13.0
