apiVersion: v1
kind: Secret
metadata:
    name: oidc-secret
    namespace: mealie
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:eIsoto+s/StNpXVp7nm4JGleZXU679MV12TSyab9JfqSZE7Ftn4uYQ==,iv:lW6HGYze3he+3arOxwa03pbud+F2kHYbg90dro8afcY=,tag:iCl5zAFkC09dYb5IHOfNdw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:wq6/chUM1dDNuMDOZIrTJwAm/PT8rarfKBTjatrMGVv23zU4gqPeypu2AV/hTJKLCYv4ZtZp3+npTqrLXhCmZd25b11faU1eOwIh5wz9OSOX2fmrMoit+hKNNbfjnbfOFvTJb6IKMa42SNQceMecRqmG1NvyDptrFhOLi2rLjVA=,iv:EZ2Pe0CFMW1mQTe730wa8p83KFgpT5JbJoAfht2s0fk=,tag:shXzrnQl4IOtVpWwURxZWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ1MwZFh6VGV0ZHR2bGlo
            Y3pUVWkvOWVZR09oc09CN3pRNHVRTDJ4ZUNnCkJraTk4YUVJQUVkSzlKMDcrNlc0
            ZWw3SkVIeU1sSnVsYk42Z3FxaVpESVkKLS0tIGFheTludjJrcWxBZk44azBKTU8x
            UHBXSXl1RTVlT0RaSHlqUk42amZmK2sK01fWkdthVdQraOVyAyF7RYpgTIf5k2qe
            Vs4qQojBLxV+YkBK5rGxkdChTbbC8xIhK7KjTG2LCELkDcutOmCREA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T15:27:20Z"
    mac: ENC[AES256_GCM,data:nNzq4GNYp1iK/ofmgGTUxHG2zFzbn867rpS9/rNq2JLkAsQIi9EM1i1ca3i0e3HqzlBCIHJtxw47DMui9K2dYbEo1rYvvD3eXVFiwXZkGLYAJapSEP4p6LcHtF5i71eB/pevqEJGfVYLHRStHZeVpbq73ea36UhDXvqBFs5UOqo=,iv:nW1mYOy+U0tnuMYKfaujpdD5y0wAga/VLv7kHjTcRYY=,tag:8gnRwlDMn32ga44njdDvVQ==,type:str]
    version: 3.13.1
