---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: projectcalico
  namespace: tigera-operator
spec:
  chart:
    spec:
      chart: tigera-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: projectcalico
      version: '3.30.*'
  interval: 5m0s
  values:
    installation:
      calicoNetwork:
        ipPools:
          - name: default-ipv4-ippool
            blockSize: 26
            cidr: 10.42.0.0/16
            encapsulation: IPIP
            natOutgoing: Enabled
            nodeSelector: all()
          - name: default-ipv6-ippool
            blockSize: 122
            cidr: 2001:cafe:42::/56
            encapsulation: None
            natOutgoing: Enabled
            nodeSelector: all()
