---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage-repo
  namespace: garage
spec:
  interval: 5m0s
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage
  ref:
    branch: main-v2
