apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - garage-bootstrap.sops.yaml
  - garage-config.yaml
  - garage-client-config.yaml
  - pvc.yaml
  - service.yaml
  - statefulset.yaml
  - bootstrap-job.yaml
