apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: cnpg-cluster
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4nqATLVfF0lx,iv:zDUsTbzIH7ahRjpVrpTzp/6XCjFasXvKA5uv5dnICs0=,tag:1b22QNM79ZQtVOIGU5WH7w==,type:str]
    password: ENC[AES256_GCM,data:C2z+JnVPc1YmrXEG2OVxHQZDCpznBRDqoXhVrOnthBfpSMN6p0IWiQ==,iv:dpGONupc/NINXLfguiITQW6gv0kqVS77wgO/iFifnaI=,tag:7uxETTRDt6u/zt3EWsV3cg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SmxJeXE3MG1KdHVld3FF
            QmN4N1pBQ0c0YytFRWdUR1lrREJ2TVVwekJBCkJwWUR2T09taUt0cS9BbFE4SStX
            Z1h3Z2huZzNFNDc0cWlENjl0bzNMdVEKLS0tIDZ6NHlIU04vaFFRVk1RNmZtbDkx
            TThZcUFZU3VQbE95WEo1Y215L3FWQ28KVfDJNtTnYaBxrIsYNb7krbYaiOaHzva/
            mh0QEnmkBJxAQI6VYo0Jt1d8AAKwzsSNCkZcTNyEyPIIJ7b9iT73Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T19:51:25Z"
    mac: ENC[AES256_GCM,data:WQkSlyZf26SiCdMDLZ4brvlpjk3Mgz7r6PogvcOBCcQMiWAj1r07W6ChD9s29C+4ZqQglht1uSEJrSSCaW8p+/bxagwpEJDGofBw13AWrXDtxrtUHQuCEo2IbmkIc9dv/8FSDLD+EHOcMNvKkuDpLTxP8rkNniWG2a0pRHBm4S4=,iv:/ohHTZbrOyUuu75boVYeZ55wrj2Tejw7Z1wDIr1ploM=,tag:FY19G3jVJuvZzU6iGLpsew==,type:str]
    version: 3.13.1
