apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: cnpg-cluster
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4nqATLVfF0lx,iv:zDUsTbzIH7ahRjpVrpTzp/6XCjFasXvKA5uv5dnICs0=,tag:1b22QNM79ZQtVOIGU5WH7w==,type:str]
    password: ENC[AES256_GCM,data:zC81y5UjVKc4N/ghhkMn5auQGx+hWLLvuGmCnHv+4IcHInVZQCsxEkV14xSgYMMv,iv:eWzNKZehr3RDsqJf9Wjq1xm0YbpHwvnTsciMgLZEL6E=,tag:E9XSCd8qoKVOQeo+NRnmMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SmxJeXE3MG1KdHVld3FF
            QmN4N1pBQ0c0YytFRWdUR1lrREJ2TVVwekJBCkJwWUR2T09taUt0cS9BbFE4SStX
            Z1h3Z2huZzNFNDc0cWlENjl0bzNMdVEKLS0tIDZ6NHlIU04vaFFRVk1RNmZtbDkx
            TThZcUFZU3VQbE95WEo1Y215L3FWQ28KVfDJNtTnYaBxrIsYNb7krbYaiOaHzva/
            mh0QEnmkBJxAQI6VYo0Jt1d8AAKwzsSNCkZcTNyEyPIIJ7b9iT73Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T15:16:24Z"
    mac: ENC[AES256_GCM,data:7pFNqFH8XDS6CFWqm/uSrGIu76DS/ktqMQ37ukcY6lEJunpmICAxLT8PQQhAsC10F9vBhuUHeh1A7gmjmj1bz8RlDRPtWjkQx8OJcWvSsARW/6Dm1npHo36rnEBdsmbj8guuo18e6mBMJuHZddDn/eOYDUo6mOhvX/bO1GhJqWU=,iv:Vw8h1fSza3+CmVqDFfIkRushA5brkxXRXxxrP3PqS44=,tag:sdIGMzF4ziIclXcpBBBA9w==,type:str]
    version: 3.13.1
