apiVersion: v1
kind: Secret
metadata:
    name: cnpg-garage-secret
    namespace: cnpg-cluster
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:owiZ9yXOBRcQkCg8Ifbb95sFkuPF+7lBdgNpUzXQbxP8dQ==,iv:vCl3KzLIytgEEqUnwx47rFJdEnEmMCKtgiVR5hVuCcw=,tag:j5kMCYXbwnOb66wyD1UHoA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3uAu366gR0RombI7rpB8iq/3e8wv/piBbKhl8g6XP0x1X7cyRqoCrJXEHJg42O9uXVqYlFScJZt7zH3ypB8vJg==,iv:Qun558hu7835OM4gpeqfFALO2NxEQjC1vTaaj3qoWAM=,tag:RQZBJs/QR2jaJDtvbAOfEg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:7lSOpmNu,iv:/1ww5UKlpkLhKkSpLgDHpcB7fJHCJGBoqHvWqE3sjdU=,tag:GyMquwwsVioAiFSeyhC1Lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad2sraElBR0ZIQU1wVTRP
            VVZuN0wzWFlOeGZvYnhGNXU0ZGNTUGNjTW0wCnBTaTFtKzZzRDNRNmpuN29yam9T
            c2tIRFVYOVlYMjF2cDJ1Y3BpNVRIdUkKLS0tIEdSb3Q0bVk1TnYxVkdReWkrbHQ4
            SkVNeTlNeEx2T01qZmc5OTVTWTF0cEUKs6VCRtlSxNNM0XKO8u2XOVwn9kAFia5R
            VyjgwHmhEQ+veiXaeeqPNMuwBquLsAXC/M44RFZ33mjjU7bDFg85/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T19:08:37Z"
    mac: ENC[AES256_GCM,data:4w6bMTlespdswWUDw5sC5fvrVMILOvEBOpqm/FvPffMDEA7Mk47GCJCfPFp7KJmcs6J5NiNscfIktu9+RqmjuYfCe8u59Bd/khGuXgHUIqZVX2MDeThr8c01bsutefNWO86sxYU53lS8vQ9aNJpl2boX+cbe2ZA6Q5YDusUgO98=,iv:pQAjlIsTRM3Lq/dGKkYDSmqnLglNrmOnbzlj8RBHaLY=,tag:r26sQS0HyAFDpjy5EKadEQ==,type:str]
    version: 3.13.3
