apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TCjWJg3gbOtvAg0qxKzBwCdGBf+jhlN/naQCbw==,iv:1Pu5Lb20rq/WAzXOnz6p1GwbRZ8a1BNSD6kEsBYAfIE=,tag:9BqwNGUBSjN9mt02G8l7CQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cnpg-superuser-password
sops:
    age:
        - recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMlJ5aHNXS2tXb2ViYmpx
            bG1OSGdxQitlMHFCV2RaYy8zTEs3QW1uSW13CkhzWHhxY0FCWDIxQjExQytGNTJk
            U2JHYmtpTVh6SEJXcGM0WDcvcTBSQk0KLS0tIElwcjJwdVlxZWhvTlJJUWkxMWY3
            YmhKQ0I2dWN1SmFDLytNZGRwRkI2eVkKAC1VgSD5y/U8HThHPeg7SRIK7bbRk7mt
            t2UW19UGTjX0kHl7D5Cw43bwFbUh3jrnE5wsws9ANm3gIxh2yIgOMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T21:36:26Z"
    mac: ENC[AES256_GCM,data:Sx/hsyoAScVl4m4etRJd0hnqWa5mBqNWgvNkH2BXzlDIJ9+abKSZDVTx49a3OuGunm3XG9JBFFafTR9irDOuSx98OkhzzaQHpAXHh+hCJcMAcVV7Qn+rhrJjVB1Gjm26y7k4G2LFDk/6flR1B5jKwT8YV2mTVmuqHWnWqHRVNLw=,iv:zpMCkV2HWomJ8IcdZvYFHiot6aBn/SE/NadETqRWTxA=,tag:GklOjhgKydk80Fh8dG5TtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
