apiVersion: v1
kind: Secret
metadata:
    name: cnpg-garage-secret
    namespace: cnpg-cluster
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:owiZ9yXOBRcQkCg8Ifbb95sFkuPF+7lBdgNpUzXQbxP8dQ==,iv:vCl3KzLIytgEEqUnwx47rFJdEnEmMCKtgiVR5hVuCcw=,tag:j5kMCYXbwnOb66wyD1UHoA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FpPRLRA1tt7IjxFTi/VElf2J8NEVUytV/IArPeU2o7sREdKLalgxlnHyOcJTeikKzicZaenu0FGwazYm1P4xWw==,iv:lP+/mjPLrXnDHXuvIqq3ztLXX4QO412ARwzmOPCCMGo=,tag:03yI01wyPpydUa1ZEcJx/w==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:7lSOpmNu,iv:/1ww5UKlpkLhKkSpLgDHpcB7fJHCJGBoqHvWqE3sjdU=,tag:GyMquwwsVioAiFSeyhC1Lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad2sraElBR0ZIQU1wVTRP
            VVZuN0wzWFlOeGZvYnhGNXU0ZGNTUGNjTW0wCnBTaTFtKzZzRDNRNmpuN29yam9T
            c2tIRFVYOVlYMjF2cDJ1Y3BpNVRIdUkKLS0tIEdSb3Q0bVk1TnYxVkdReWkrbHQ4
            SkVNeTlNeEx2T01qZmc5OTVTWTF0cEUKs6VCRtlSxNNM0XKO8u2XOVwn9kAFia5R
            VyjgwHmhEQ+veiXaeeqPNMuwBquLsAXC/M44RFZ33mjjU7bDFg85/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T13:54:45Z"
    mac: ENC[AES256_GCM,data:q3PQecibtnJM6t1sn/5eqYCI5uvCFKzrUKw4N61mJQ6OR0Ef4m7/OsMO+GLlZFavFkMADokgFyhab0c2dGJJkLyjS5yNyCz4vQTtmY7PjCsBpUBVU0tOkyVrnwqBDzFpFyAir3yNrXOz5RYsNeABxUV2ofqdcRgtz5kvvlyFvKg=,iv:f6BZZLcIHkkVeTrkQXIYZIskHKq3DYy3noCnLPHr+4Y=,tag:uht9WFZ4/VktR4u77OIP3w==,type:str]
    version: 3.13.3
