apiVersion: v1
kind: Secret
metadata:
    name: immich-db-secret
    namespace: cnpg-cluster
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:nBlquCPU,iv:Z5gIATzVqPMfDvksib5Pa5fzt39Y29Ua0Ba5rKIoGqo=,tag:9E+hvwU7w6rOgnBQB6Q79g==,type:str]
    password: ENC[AES256_GCM,data:wWqcLfERbUP4q9XAyupCZ3ELOcI=,iv:/9X1db8/67JxQBso2UsYb6cTzvF8vH6/h8DG/vS/emk=,tag:7jD4OVAWE0C3CN2jRDunhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSDY2eWNDcFJMYW8rMXVX
            MVZpVGlpNjI4SDMxWUhxRG9OeUF6OWlQclF3CjA5LzJkcjU1WU9aUzR2emNPbHVQ
            bWduOTFlQnFneFFXYzlyWlZhanB2L1EKLS0tIGhnSzdZQ0NCRWhTdHdHaU92T0p2
            dG9QK0dSd3dkc3B3WU9HbWZ4L3pJUUUKE8ufuGcvZc4WSWww+IQOS1u42GDfLxsk
            EhBdKH8sY7m8E+ixAlCjq1SbFc/VIr5i6FGymYA8+PRo2Es1T/AEAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T07:35:08Z"
    mac: ENC[AES256_GCM,data:4+FtCM56D800WYtj0MR7qYhJjIHGNEA/jv9oeoY7CEYOUDAizfTfo8iCFYOQ4gTvxrvdvpgzCzW3bnQin0wFPJaCdu1ADn1CxHTcF9pLXLU+yE7RXecOPKYGcfHOV3qvIJgvl6vdnzxo4Qo0MRCLVKHu2f6agcCxFzr59pUeQ40=,iv:ZzxHNiHERAdzYdCq/z7nyV5VPGi+TJ8mwdSD1EhSdyI=,tag:pcW8K8FV2m9mfc6ZrIg2Qg==,type:str]
    version: 3.13.1
