apiVersion: v1
data:
    password: ENC[AES256_GCM,data:uXmlaftmKKqboi0RKQsLxsWsqjdngSw7zOJhyg==,iv:TEjoj2m/zexR50VAAoLZ8uwW88ycqeUWpnAisqpmhKU=,tag:2rXd3KYxacLyQqYbDYJ/vA==,type:str]
    username: ENC[AES256_GCM,data:ZUgUHftBCH8=,iv:/FNd6H4CEZ8xCz28M6Ltamfjd4OKY1wlqXf31mHpWNY=,tag:H9SgGU8o5FIAEdzieINVZw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: scrapy-db-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUVZJWWVCU0dBVDZtR2Vj
            N2wwbmVqV1ZIYmFVREtsNWF6aHhZMUJSSmhRCnNXaGtaZERQUnBVMGVQVk96MVk1
            c2NRY09BWEtBMWRHTm96VWZYajYra3MKLS0tIFFSNTdZR1lhMXowdHBCV05ISnJH
            L3lsZzJkd0x1dTczZ0poaW1RcDJzbUUKzvcbLNq3JuM2crZNienJB7uxyfFaRy1e
            Px8US2+H19dM7oeW1p3//cTxYP7/hoM166+iJY7rXcuwpqRuO65Idg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:58:51Z"
    mac: ENC[AES256_GCM,data:Bc4fyJC+qOeM9oQzoMha/ZHHkzJaMdXLkxcl+L5dgPZ5Lc/8I5nqMQaYBGs6+xonsZ8AWrdrCRlGD3G1OT/QAsfWNZl1IMlFyqx8hLh0rdTmth9GN0vVELc3vV8DBLHInLSLoWBQZpyfONGer5TwHTPEZLrqYS+7buSf2kbvRMc=,iv:Mx7oAYxGX/a4MUZK7Vh3J5tzKHKWJ3IPa48jHmxi5E0=,tag:zqGZF7siCFGhX1lHIYbSuQ==,type:str]
    version: 3.13.1
