apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dns-pool
spec:
  addresses:
    - 192.168.2.16/32
    - fd87:b03b:2a6c::1eed:6fff:fe71:43b9/128
  serviceAllocation:
    priority: 1
    namespaces:
      - blocky
