apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-server
  labels:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sftp-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sftp-server
    spec:
      containers:
        - name: sftp
          image: atmoz/sftp:latest
          ports:
            - containerPort: 22
              name: sftp
          args:
            - "uploader::1000:1000"
          volumeMounts:
            - name: audiobooks
              mountPath: /home/uploader/audiobooks
            - name: fotos
              mountPath: /home/uploader/fotos
            - name: music
              mountPath: /home/uploader/music
            - name: videos
              mountPath: /home/uploader/videos
            - name: ssh-keys
              mountPath: /home/uploader/.ssh/keys/id_ed25519.pub
              subPath: id_ed25519.pub
              readOnly: true
            - name: ssh-keys
              mountPath: /etc/ssh/ssh_host_ed25519_key
              subPath: ssh_host_ed25519_key
              readOnly: true
            - name: ssh-keys
              mountPath: /etc/ssh/ssh_host_rsa_key
              subPath: ssh_host_rsa_key
              readOnly: true
      volumes:
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobooks-iscsi-pvc
        - name: fotos
          nfs:
            server: 192.168.2.178
            path: /nfs/Fotos
        - name: music
          nfs:
            server: 192.168.2.178
            path: /nfs/Musik
        - name: videos
          nfs:
            server: 192.168.2.178
            path: /nfs/Videos
        - name: ssh-keys
          secret:
            secretName: sftp-keys
            defaultMode: 0600
