apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
commonLabels:
  app: pihole
  app.kubernetes.io/part-of: pihole
resources:
  - namespace.yaml
  - sealed-pihole-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
