apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
labels:
  - includeSelectors: true
    pairs:
      app: pihole
      app.kubernetes.io/part-of: pihole
resources:
  - namespace.yaml
  - pihole-secret.sops.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
