apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - namespace.yaml
  - storage-class.yaml
  - sealed-minio-login-secret.yaml
  - helmrepo.yaml
  - helmrelease.yaml
