apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - namespace.yaml
  - minio-login-secret.sops.yaml
  - minio-user.sops.yaml
  - helmrepo.yaml
  - helmrelease.yaml
