apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-gpu
resources:
  - namespace.yaml
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/gpu_plugin?ref=v0.34.0
