apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-scrapydb
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  scrapydb.yaml: |
    apiVersion: 1
    datasources:
      - name: scrapydb
        uid: scrapydb
        type: grafana-postgresql-datasource
        access: proxy
        url: cnpg-cluster-rw.cnpg-cluster.svc:5432
        database: scrapydb
        user: scrapy
        jsonData:
          sslmode: disable
          postgresVersion: 1600
        secureJsonData:
          password: $__env{SCRAPY_DB_PASSWORD}
        editable: false
