apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ueVTqS2in/WJ4DCWiQdKZHjkMp5zOUoksAG1vaDGvzJbwrvNadsjMA==,iv:j7ODNjWpHOqKNPOJX6W4vI7F+l9Htcs3/1U/iJjiGIE=,tag:SpXYK25ady4gq08kho2B7Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:KgY2TsJfUei3KZeisAPmJ3FfFtxyGL3duGVPKN7St/UVxan9+6661NR8S8pCHE+kdGY6GrqPWcKH3S20JkBx/vl2glxH52AgoiftQ1gnwqNvZXO7l8eld0ZDu8YgnZp45bcBOrvW1juYYCEJTN2VMOTvMT4Vkbrw1yoPcQSIGdo=,iv:qJ0mM1ZDVtpo3KwUIAoLo4e6106Oh585roBRmw9eQPU=,tag:gRMLchC/ppgh/Stajx5vVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dUQrZk95MkxJaXdkMDVi
            MEx2MFpISW53eSs1UUxnTHhoVHhZN1I5RUdJClp0aXZnT2tIUXJrK3c5L0ExanJr
            Sm5wbXpWVGEwQ0s3Y3JKdW85OE45UE0KLS0tIHBxNzM0RlREaVVmTWJ2VE8yUzBS
            T0IzbG8yUk1RcUt0MU5BZVJOV203K1kKK5nl+3h9J4ii6Ub/v5cU9wbBBIQBPA/N
            hHYaem+6DQsYhvYAkWqfvefN2iL+vEKVWtYZFm6m+AdbN5IshhgCQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T15:27:20Z"
    mac: ENC[AES256_GCM,data:5bJjvSxAxZaM9zib6knesNJA+fcye7t0wrjWLOvoN2NxTmgw5z2RcHixFURSu1KZtLOwvfuOZt5MHpu5ffRL8CfY8cPInMgR8AL2F6GBxUyqZH1uJMbMIXVMbCFx219gyAegZpJOW7FIOOVmeBfWqkJdXaOOxGliM5NQmlZDNiM=,iv:NsClPwqKv5VCOfUuUA5QBBUebor79MuGi5jCeyQc/Fg=,tag:YAsxEYsGgxA92GwmEC6qaQ==,type:str]
    version: 3.13.1
