apiVersion: v1
kind: Secret
metadata:
    name: scrapy-grafana
    namespace: monitoring
data:
    SCRAPY_DB_PASSWORD: ENC[AES256_GCM,data:dVaCZsNGa/k83OxpN28eGDelmg6czyd4EaFpyg==,iv:NTISfu7Ljsto2oUGuGntL50gLw3r+6ZfeufWGdpUD4A=,tag:aWUgfvq2LbJ0fyfBkGs7Lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYUdhV2VncjBveXJoUXJC
            VEI4YzVOczRTOFFLb3gveFo2clV4TWdZUmdRCi92aTJvL0RaYXBDbG9HZlFUUEQ4
            bzh1b0F1aWJhUkt1WkE4c213RWNvTzAKLS0tIG9tMUh4Q2xyQVFkeUlRQnZiY3NR
            VjZvQkpMMG00akdiczdCdXpWVWQ4V1UK8CfUHzsJk3CGhhxpv5HS2AtLY4FNL/R1
            PjpQILWlHeCyFGNi63ydzWbv6OfrfdVsKOTJDXcU3zWV8X8KcY83aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:58:23Z"
    mac: ENC[AES256_GCM,data:NAixBPNxaGT1uswUct4/TSCY2GPqXKKLpTWiDWwsEshNBMlUpFvIrw4cf68ZrJ/piR/50rDoZhpIFB3yp0HIn2adDk5kz5vHvdpz5yfymU+cFO6r4vsZy4Zs6SaTJiUk+MEuYoB1dWj3EIv//UjLjtbb3nYqBhqcII329HZbgnc=,iv:0FvPOeYfzJiZijYUSLsuW+9rpD85/sqoliA7X8fv/DU=,tag:OM53GkiLER1mEyhBS3yxOw==,type:str]
    version: 3.13.1
