apiVersion: v1
kind: Secret
metadata:
    name: scrapy-grafana
    namespace: monitoring
type: Opaque
stringData:
    SCRAPY_DB_PASSWORD: ENC[AES256_GCM,data:gcm2MuPMY9QHp0HGre65iPD2ArI=,iv:d9RoolMGTutVcBZYpyEVTi+wlJBL8g5AV5oGFz+AJws=,tag:ELEZF6G+tIV25XhwV3zQ5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYUdhV2VncjBveXJoUXJC
            VEI4YzVOczRTOFFLb3gveFo2clV4TWdZUmdRCi92aTJvL0RaYXBDbG9HZlFUUEQ4
            bzh1b0F1aWJhUkt1WkE4c213RWNvTzAKLS0tIG9tMUh4Q2xyQVFkeUlRQnZiY3NR
            VjZvQkpMMG00akdiczdCdXpWVWQ4V1UK8CfUHzsJk3CGhhxpv5HS2AtLY4FNL/R1
            PjpQILWlHeCyFGNi63ydzWbv6OfrfdVsKOTJDXcU3zWV8X8KcY83aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:11:09Z"
    mac: ENC[AES256_GCM,data:N7aSQ8n5KrCHAQCZY/7SoB+MSrq6Fw9TjEEeZ06uYibbqnYnEWXdLkF1P395RCc27PsqHkLQ0IR6beg8fXJmhupt5ncQi9kNAffflZRLsq0weCZCy16Gj7nL3scUPm3IFoYELfyzSssesJHbfM5F6FpwzRoh+mJUO5tmOi8Pbcw=,iv:xoW1GZEs1eDeenfYC91h8uAXZI1oUZpKobXItvhetpk=,tag:trbkrj8/03XHjJTlpaZZHg==,type:str]
    version: 3.13.1
