apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
labels:
  - includeSelectors: true
    pairs:
      app: homeassistant
      app.kubernetes.io/part-of: homeassistant
sortOptions:
  order: fifo
resources:
  - namespace.yaml
  - ha-configuration.sops.yaml
  - homeassistant-data.yaml
  - webserver-deployment.yaml
  - webserver-service.yaml
  - ingress.yaml
