---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-release
  namespace: cnpg-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: v0.24.0
  interval: 5m0s
  values:
    replicaCount: 3
