---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-provisioner-release
  namespace: nfs-subdir-external-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
      version: 4.0.18
  interval: 5m0s
  values:
    nfs:
      server: 192.168.2.146
      path: /mnt/Personal/ClusterBackups/
    storageClass:
      create: true
      name: nfs
      reclaimPolicy: Retain
    securityContext:
      enabled: true
      runAsUser: 501
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "Always"
    podSecurityContext:
      enabled: true
      runAsUser: 501
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "Always"
