apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s-helmrepo.yaml
  - blocky
  - scraper
  - jellyfin
  - mealie
  - paperless
  - homeassistant
  - mosquitto
  - zigbee2mqtt
  - homepage
